# Generated by Django 3.0.5 on 2020-04-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isActive',
            field=models.NullBooleanField(default=True),
        ),
    ]
