# Generated by Django 3.0.5 on 2020-04-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_author_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
