# Generated by Django 3.0.5 on 2020-04-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200425_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='adddres',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='book',
            name='publicate_date',
            field=models.DateField(verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='书籍'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(verbose_name='网址'),
        ),
    ]
