# Generated by Django 3.0.5 on 2020-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200425_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload', verbose_name='头像'),
        ),
    ]
