# Generated by Django 3.0.5 on 2020-04-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_wife_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='authors',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Author', verbose_name='对象'),
        ),
    ]
